name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  filter_list: ^1.0.2
  file_picker: ^8.0.3
  provider: ^6.0.0
  flutter_sms:
    git:
      url: https://github.com/fluttercommunity/flutter_sms.git
      ref: master
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_local_notifications: ^15.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
